### ISSUE TITLE
Device Bean always showing devices as 0

### ISSUE THREAD

**Issue by mytuya** [TuyaInc/tuyasmart_android_sdk#10]
List<DeviceBean> devBean = TuyaHomeSdk.getDataInstance().getHomeDeviceList(homeId); returns a size of 0 even though a doorbell has been added to it

**Comment by taoyuanxiaoqi** [comment]
can you show me your account number?

**Comment by mytuya** [comment]
Do you mean Home Id? Or login name?

**Comment by mytuya** [comment]
You haven't provided a solution. You cannot close this issue.
