### ISSUE TITLE
获取category和获取数据点的历史统计数据

### ISSUE THREAD

**Issue by xyUp** [TuyaInc/tuyasmart_android_sdk#17]
1.添加设备后，获取到的DeviceBean的category没有值
2.获取数据点的历史统计数据，接口参数有误
![image](https://user-images.githubusercontent.com/14787839/59488193-77191980-8eb1-11e9-87c9-5788893a17bd.png)
以上图片是我根据文档写的代码，返回错误
s: PARAMS_ILLEGAL_OR_DATA_ILLEGAL   s1: 参数或数据不合法

**Comment by NextApp** [comment]
再试一下看看

**Comment by NextApp** [comment]
是由于平台配置没有开启导致的

**Comment by xyUp** [comment]
还是不行啊，两个问题都和原来一样 @NextApp

**Comment by xyUp** [comment]
同一种设备应该是通过可以通过category这个字段判断的吧，可以productId字段判断吗？
