### ISSUE TITLE
关于废弃代码

### ISSUE THREAD

**Issue by Anthrax1985** [TuyaInc/tuyasmart_android_sdk#2]
Demo一些无用的类有严重的误导嫌疑，有空请把不要的代码删掉，省得浪费大家时间
![image](https://cloud.githubusercontent.com/assets/15762583/23296645/05698eaa-fab1-11e6-93bb-372a6f638938.png)

**Comment by helloworkcupid** [comment]
注册，登录了，提示“非法请求”，请问如何处理呢？

**Comment by NextApp** [comment]
使用新版本SDK
