### ISSUE TITLE
错误代码

### ISSUE THREAD

**Issue by AIlll** [TuyaInc/tuyasmart_android_sdk#5]
错误代码有没有说明啊，有时候出现错误不清楚原因是什么，有说明的话更好定位错误在哪

**Comment by NextApp** [comment]
//Business
    public static final String BUSINESS_NETWORK_UNKNOWN = "101";        //网络异常
    public static final String BUSINESS_JSON_EXCEPTION = "102";         //json转义失败
    public static final String BUSINESS_NETWORK_ERROR = "103";          //网络错误，无法访问网络
    public static final String BUSINESS_TIME_ERROR = "104";             //手机时钟不对 https证书过期
    public static final String BUSINESS_NEED_LOGIN = "105";             //登陆需要session信息
    public static final String BUSINESS_IO_EXCEPTION = "106";           //同步io错误

    public static final String STATUS_FAILURE_WITH_NETWORK_ERROR = "1001";
    public static final String STATUS_FAILURE_WITH_BIND_GWIDS = "1002";
    public static final String STATUS_FAILURE_WITH_BIND_GWIDS_1 = "1003";
    public static final String STATUS_FAILURE_WITH_GET_TOKEN = "1004";
    public static final String STATUS_FAILURE_WITH_CHECK_ONLINE_FAILURE = "1005";
    public static final String STATUS_FAILURE_WITH_OUT_OF_TIME = "1006";
    public static final String STATUS_DEV_CONFIG_ERROR_LIST = "1007";

    public static final String ERROR_PHONE_NUMBER_ERROR = "1100";       //手机号码不正确
    public static final String ERROR_PHONE_CODE_ERROR = "1101";       //验证码不正确
    public static final String ERROR_ROM_UPDATE = "1102";    //升级

    //Device
    public static final String DEV_PUBLISH_DPS_BY_INTRANET_FAILURE_WITH_OFFLINE = "10201"; //局域网不在线
    public static final String DEV_PUBLISH_DPS_BY_CLOUD_FAILURE_WITH_OFFLINE = "10202"; //云端不在线
    public static final String DEV_PUBLISH_DPS_FAILURE_WITH_OFFLINE = "10203";          //设备不在线
    public static final String DEV_PUBLISH_DPS_FAILURE_WITH_DP_FORMAT_ERROR = "11001";  //下发的command格式有误
    public static final String DEV_PUBLISH_DPS_FAILURE_WITH_DEV_REMOVED = "11002";      //设备已被移除
    public static final String DEV_PUBLISH_DPS_FAILURE_WITH_AES_BYTES_IS_NULL = "11003";      //aes==null
    public static final String DEV_PUBLISH_DPS_FAILURE_WITH_SIGN_IS_NULL = "11004";//sign==null
    public static final String DEV_PUBLISH_ERROR = "11005";//下发失败
    public static final String DEV_PUBLISH_DPS_DATA_IS_NULL = "11009";//

    //message
    public static final String MESSAGE_RECEIVED_PARSE_ERROR = "12001";      //数据解析失败
    public static final String MESSAGE_RECEIVED_SIGN_NOT_EQUAL = "12002";   //签名不一致
    public static final String MESSAGE_RECEIVED_DATA_DATED = "12003";        //    数据过期
    public static final String MESSAGE_RECEIVED_PROTOCOL_NOT_EXIST = "12004";//协议号不存在

**Comment by NextApp** [comment]
先在这里看一下，下个版本补充到文档里面
