### ISSUE TITLE
How can I add appkey and appsecret to the program?

### ISSUE THREAD

**Issue by quangchungnguyen** [TuyaInc/tuyasmart_android_sdk#6]

**Comment by quangchungnguyen** [comment]
I use this source code and use Android studio to compile. However, the program notice that appkey and appsecret is empty. Where can I get these key? How can I add appkey and appsecret to the program?
Thank you

**Comment by NextApp** [comment]
you can get help from here . https://docs.tuya.com/en/app/app-sdk/android-sdk.html

**Comment by miguelcamargo9** [comment]
@quangchungnguyen could you get the keys?

**Comment by quangchungnguyen** [comment]
Yes, I got the key. I'm running test the program. very thank you for the help @NextApp
