### ISSUE TITLE
How can I get PersonBean class or relationId for sharing a device?

### ISSUE THREAD

**Issue by serhiitereshchenko** [TuyaInc/tuyasmart_android_sdk#8]
To use method addDevShare(String devId, long relationId, IResultCallback callback)) I need relationId. Can you please explain how can I get it? Can I get it by user uuid?

**Comment by blitzfeng** [comment]
If you first share a device to someone,you need use this method `void addShare(String countryCode, String userAccount, ShareIdBean bean, boolean autoSharing, IAddShareWithInfoCallback callback);`
If you have shared a device to someone,you can use the method`queryUserShareList ` to get relationId,then you can use `addDevShare` @SsIDit
