### ISSUE TITLE
Issues with tuyasdk-home-2.6.4r95

### ISSUE THREAD

**Issue by mytuya** [TuyaInc/tuyasmart_android_sdk#9]
I am using the tuyasdk-home-2.6.4r95 aar file. It has the following issues.  I have imported the aar file. 

I am trying to get activator token using

 TuyaActivator.getInstance().getActivatorToken (FamilyManager.getInstance().getCurrentHomeId(),new ITuyaActivatorGetToken() {
                    @Override
                    public void onSuccess(String token) {
                        //获取token成功
                    }

                    @Override
                    public void onFailure(String s, String s1) {
                        //获取token失败
                    }
                });

The error I get is shown in the screen below. It cannot find TuyaActivator and FamilyManager.
<img width="735" alt="screen shot 2018-08-30 at 12 47 43" src="https://user-images.githubusercontent.com/42831561/44838039-d5de1100-ac58-11e8-91ea-c9040d0b5496.png">

After doing the following:
 TuyaCameraActivatorBuilder builder = new TuyaCameraActivatorBuilder();
                builder.setSsid(etSSID.getText().toString());
                builder.setToken(token);
                builder.setPassword(etKey.getText().toString());
                builder.setTimeOut(100);
                builder.setListener(mListener);

I set the ITuyaCameraDevActivator mTuyaActivator = ITuyaCameraDevActivator.newCameraDevActivator(builder);
                mTuyaActivator.createQRCode();
                mTuyaActivator.start();

It gives me the error newCameraDevActivator not found. Please see the screenshot below.

<img width="945" alt="screen shot 2018-08-30 at 13 08 56" src="https://user-images.githubusercontent.com/42831561/44838014-c8288b80-ac58-11e8-83f7-35f25bb1ca0d.png">

**Comment by shubham3107** [comment]
mTuyaActivator = TuyaActivator.getInstance().newActivator(new ActivatorBuilder()

not working in new SDK
